'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const TYPES={manual:{name:'Manual Operation',icon:'●',colour:'#f4c400',desc:'Operator performs manual work'},automatic:{name:'Automatic Machine',icon:'▣',colour:'#76cf37',desc:'CNC, machine or automatic process'},walk:{name:'Walking / Transfer',icon:'🚶',colour:'#68a9e8',desc:'Operator walks with component'},inspection:{name:'Inspection',icon:'⌕',colour:'#ec8c23',desc:'Check or measure component'},buffer:{name:'Buffer / Queue',icon:'◆',colour:'#a978da',desc:'Temporary storage or queue'}};
const builtIns=[
{id:'manual',type:'manual',name:'Manual Operation',cycle:2,cost:25},
{id:'automatic',type:'automatic',name:'Automatic Machine',cycle:6.5,cost:75},
{id:'walk',type:'walk',name:'Walking / Transfer',cycle:.75,cost:25},
{id:'inspection',type:'inspection',name:'Inspection',cycle:5,cost:30},
{id:'buffer',type:'buffer',name:'Buffer / Queue',cycle:0,cost:0}
];
let state={project:{},nodes:[],links:[],customResources:[],zoom:1,panX:40,panY:40,selectedId:null,selectedLink:null,mode:'select'};
let undoStack=[],redoStack=[],linkStart=null,pointer=null,toastTimer;
const els={world:$('#canvasWorld'),viewport:$('#canvasViewport'),nodes:$('#nodeLayer'),links:$('#linkLayer'),form:$('#taskForm'),empty:$('#emptyInspector'),inspector:$('#inspectorPanel'),library:$('#libraryPanel')};
function uid(prefix='n'){return prefix+Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function clone(v){return JSON.parse(JSON.stringify(v))}
function snapshot(){undoStack.push(clone({nodes:state.nodes,links:state.links,customResources:state.customResources}));if(undoStack.length>60)undoStack.shift();redoStack=[]}
function restore(s){state.nodes=s.nodes||[];state.links=s.links||[];state.customResources=s.customResources||[];state.selectedId=null;renderAll()}
function undo(){if(!undoStack.length)return;redoStack.push(clone({nodes:state.nodes,links:state.links,customResources:state.customResources}));restore(undoStack.pop())}
function redo(){if(!redoStack.length)return;undoStack.push(clone({nodes:state.nodes,links:state.links,customResources:state.customResources}));restore(redoStack.pop())}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),1800)}
function allResources(){return [...builtIns,...state.customResources]}
function resourceByType(type){return allResources().find(r=>r.type===type)||builtIns[0]}
function renderLibrary(){const box=$('#resourceLibrary');box.innerHTML='';allResources().forEach(r=>{const t=TYPES[r.type]||{name:r.name,icon:'■',colour:r.colour||'#f4c400',desc:'Custom resource'};const card=document.createElement('div');card.className='resource-card';card.draggable=true;card.dataset.resource=JSON.stringify(r);card.innerHTML=`<div class="resource-icon" style="color:${r.colour||t.colour}">${t.icon}</div><div><strong>${r.name}</strong><span>${t.desc}</span></div>`;card.addEventListener('dragstart',e=>e.dataTransfer.setData('application/x-resource',JSON.stringify(r)));card.addEventListener('click',()=>addNodeFromResource(r,visibleWorldCentre()));box.appendChild(card)})}
function visibleWorldCentre(){const rect=els.viewport.getBoundingClientRect();return{x:(rect.width/2-state.panX)/state.zoom-105,y:(rect.height/2-state.panY)/state.zoom-66}}
function addNodeFromResource(r,pos){snapshot();const t=TYPES[r.type]||TYPES.manual;state.nodes.push({id:uid(),name:r.name,type:r.type,cycle:+r.cycle||0,cost:+r.cost||0,notes:'',x:Math.max(0,pos.x),y:Math.max(0,pos.y),colour:r.colour||t.colour});state.selectedId=state.nodes.at(-1).id;renderAll();openInspector();toast('Resource added')}
function renderAll(){renderLibrary();renderNodes();renderLinks();renderInspector();updateTransform();updateStatus();saveAutosave()}
function renderNodes(){els.nodes.innerHTML='';state.nodes.forEach((n,i)=>{const t=TYPES[n.type]||TYPES.manual;const el=document.createElement('div');el.className='task-node'+(n.id===state.selectedId?' selected':'')+(n.id===linkStart?' link-source':'');el.dataset.id=n.id;el.style.cssText=`left:${n.x}px;top:${n.y}px;--node-color:${n.colour||t.colour}`;el.innerHTML=`<div class="node-number">${i+1}</div><div class="node-main"><div class="node-icon">${t.icon}</div><div><div class="node-title">${escapeHtml(n.name)}</div><div class="node-type">${escapeHtml(t.name)}</div></div></div><div class="node-data"><span>Cycle Time</span><strong>${(+n.cycle).toFixed(2)} min</strong><span>Cost / Hr</span><strong>£${(+n.cost).toFixed(2)}</strong></div><span class="port in"></span><span class="port out"></span>`;el.addEventListener('pointerdown',nodePointerDown);el.addEventListener('dblclick',()=>{state.selectedId=n.id;renderAll();openInspector()});els.nodes.appendChild(el)})}
function linkPath(a,b){const aw=210,ah=132;let x1=a.x+aw,y1=a.y+ah/2,x2=b.x,y2=b.y+ah/2;const dx=Math.max(55,Math.abs(x2-x1)*.48);return `M ${x1} ${y1} C ${x1+dx} ${y1}, ${x2-dx} ${y2}, ${x2} ${y2}`}
function renderLinks(){els.links.innerHTML=`<defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="8" markerHeight="8" orient="auto-start-reverse"><path d="M 0 0 L 10 5 L 0 10 z" fill="#d5dadd"/></marker></defs>`;state.links.forEach(l=>{const a=state.nodes.find(n=>n.id===l.from),b=state.nodes.find(n=>n.id===l.to);if(!a||!b)return;const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d',linkPath(a,b));p.setAttribute('class','link'+(state.selectedLink===l.id?' selected':''));p.dataset.id=l.id;p.addEventListener('pointerdown',e=>{e.stopPropagation();state.selectedLink=l.id;state.selectedId=null;renderAll()});els.links.appendChild(p)})}
function nodePointerDown(e){e.stopPropagation();const id=e.currentTarget.dataset.id;if(state.mode==='link'){if(!linkStart){linkStart=id;state.selectedId=id;toast('Select the destination task')}else if(linkStart!==id){if(!state.links.some(l=>l.from===linkStart&&l.to===id)){snapshot();state.links.push({id:uid('l'),from:linkStart,to:id})}linkStart=null;state.mode='select';setMode('select');renderAll()}return}state.selectedId=id;state.selectedLink=null;const n=state.nodes.find(x=>x.id===id);pointer={kind:'node',id,startX:e.clientX,startY:e.clientY,origX:n.x,origY:n.y,moved:false};e.currentTarget.setPointerCapture(e.pointerId);renderAll();openInspector()}
function pointerMove(e){if(!pointer)return;if(pointer.kind==='node'){const n=state.nodes.find(x=>x.id===pointer.id);const dx=(e.clientX-pointer.startX)/state.zoom,dy=(e.clientY-pointer.startY)/state.zoom;if(Math.abs(dx)+Math.abs(dy)>3&&!pointer.moved){snapshot();pointer.moved=true}n.x=Math.max(0,pointer.origX+dx);n.y=Math.max(0,pointer.origY+dy);renderNodes();renderLinks()}else if(pointer.kind==='pan'){state.panX=pointer.origX+e.clientX-pointer.startX;state.panY=pointer.origY+e.clientY-pointer.startY;updateTransform()}}
function pointerUp(){if(pointer?.moved)saveAutosave();pointer=null}
function canvasPointerDown(e){if(e.target.closest('.task-node')||e.target.closest('.link'))return;state.selectedId=null;state.selectedLink=null;renderAll();pointer={kind:'pan',startX:e.clientX,startY:e.clientY,origX:state.panX,origY:state.panY};els.viewport.setPointerCapture(e.pointerId)}
function updateTransform(){els.world.style.transform=`translate(${state.panX}px,${state.panY}px) scale(${state.zoom})`;$('#zoomLabel').textContent=Math.round(state.zoom*100)+'%'}
function zoomAt(factor,cx,cy){const old=state.zoom,nz=Math.min(2.5,Math.max(.35,old*factor));const rect=els.viewport.getBoundingClientRect(),x=cx??rect.left+rect.width/2,y=cy??rect.top+rect.height/2;const wx=(x-rect.left-state.panX)/old,wy=(y-rect.top-state.panY)/old;state.zoom=nz;state.panX=x-rect.left-wx*nz;state.panY=y-rect.top-wy*nz;updateTransform()}
function fitAll(){if(!state.nodes.length){state.zoom=1;state.panX=40;state.panY=40;updateTransform();return}const minX=Math.min(...state.nodes.map(n=>n.x)),minY=Math.min(...state.nodes.map(n=>n.y)),maxX=Math.max(...state.nodes.map(n=>n.x+210)),maxY=Math.max(...state.nodes.map(n=>n.y+132));const r=els.viewport.getBoundingClientRect(),pad=55;state.zoom=Math.min(1.35,Math.max(.35,Math.min((r.width-pad*2)/(maxX-minX),(r.height-pad*2)/(maxY-minY))));state.panX=pad-minX*state.zoom;state.panY=pad-minY*state.zoom;updateTransform()}
function setMode(mode){state.mode=mode;linkStart=null;$$('.toolbar [data-action]').forEach(b=>b.classList.toggle('active',b.dataset.action===mode));$('#modeHint').textContent=mode==='link'?'Link mode: choose start and destination':'Select mode';renderNodes()}
function renderInspector(){const n=state.nodes.find(x=>x.id===state.selectedId);els.form.classList.toggle('hidden',!n);els.empty.classList.toggle('hidden',!!n);if(!n)return;const t=TYPES[n.type]||TYPES.manual;$('#taskName').value=n.name;$('#taskType').value=n.type;$('#cycleTime').value=n.cycle;$('#costPerHour').value=n.cost;$('#taskNotes').value=n.notes||'';$('#previewIcon').textContent=t.icon;$('#previewIcon').style.color=n.colour||t.colour;$('#previewTitle').textContent=n.name;$('#previewType').textContent=t.name}
function updateSelectedFromForm(){const n=state.nodes.find(x=>x.id===state.selectedId);if(!n)return;snapshot();n.name=$('#taskName').value.trim()||'Untitled Task';n.type=$('#taskType').value;n.cycle=Math.max(0,+$('#cycleTime').value||0);n.cost=Math.max(0,+$('#costPerHour').value||0);n.notes=$('#taskNotes').value;n.colour=(TYPES[n.type]||TYPES.manual).colour;renderAll()}
function duplicateSelected(){const n=state.nodes.find(x=>x.id===state.selectedId);if(!n)return;snapshot();const c={...clone(n),id:uid(),name:n.name+' Copy',x:n.x+35,y:n.y+35};state.nodes.push(c);state.selectedId=c.id;renderAll();openInspector()}
function deleteSelected(){if(state.selectedLink){snapshot();state.links=state.links.filter(l=>l.id!==state.selectedLink);state.selectedLink=null;renderAll();return}if(!state.selectedId)return;snapshot();state.links=state.links.filter(l=>l.from!==state.selectedId&&l.to!==state.selectedId);state.nodes=state.nodes.filter(n=>n.id!==state.selectedId);state.selectedId=null;renderAll()}
function updateStatus(){const cycle=state.nodes.reduce((a,n)=>a+(+n.cycle||0),0),cost=state.nodes.reduce((a,n)=>a+(+n.cost||0),0);$('#taskCount').textContent=`Tasks: ${state.nodes.length}`;$('#cycleTotal').textContent=`Total cycle: ${cycle.toFixed(2)} min`;$('#costTotal').textContent=`Total cost/hr: £${cost.toFixed(2)}`;const n=state.nodes.find(x=>x.id===state.selectedId);$('#selectionStatus').textContent=n?`Selected: ${n.name}`:state.selectedLink?'Link selected':'No task selected'}
function collectProject(){return{projectName:$('#projectName').value,projectRevision:$('#projectRevision').value,annualVolume:+$('#annualVolume').value||0,customerName:$('#customerName').value,customerContact:$('#customerContact').value,componentName:$('#componentName').value,partNumber:$('#partNumber').value,shiftPattern:$('#shiftPattern').value,hoursPerShift:+$('#hoursPerShift').value||0}}
function applyProject(p={}){Object.entries(p).forEach(([k,v])=>{const el=$('#'+k);if(el)el.value=v})}
function projectFile(){return{format:'ManufacturingFlowDesigner',version:1,stage:1,savedAt:new Date().toISOString(),project:collectProject(),nodes:state.nodes,links:state.links,customResources:state.customResources}}
function saveAutosave(){try{localStorage.setItem('mfd-stage1-autosave',JSON.stringify(projectFile()))}catch{}}
function saveLocal(){saveAutosave();toast('Project saved on this device')}
function exportFile(){const data=JSON.stringify(projectFile(),null,2),blob=new Blob([data],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(($('#projectName').value||'ManufacturingFlow').replace(/[^a-z0-9_-]+/gi,'_'))+'.mflow';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Project exported')}
function importData(data){if(data.format!=='ManufacturingFlowDesigner'&&!Array.isArray(data.nodes))throw new Error('Not a valid project file');snapshot();state.nodes=data.nodes||[];state.links=data.links||[];state.customResources=data.customResources||[];applyProject(data.project||{});state.selectedId=null;renderAll();fitAll();toast('Project opened')}
function newProject(){if(state.nodes.length&&!confirm('Start a new project? Unsaved changes on this device will be replaced.'))return;snapshot();state.nodes=[];state.links=[];state.customResources=[];applyProject({projectName:'New Project',projectRevision:'A',annualVolume:0,customerName:'',customerContact:'',componentName:'',partNumber:'',shiftPattern:'1 Shift',hoursPerShift:8});renderAll();state.zoom=1;state.panX=40;state.panY=40;updateTransform()}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function openInspector(){if(innerWidth<=1150)els.inspector.classList.add('open')}
function sample(){const seq=[['Unload Material','manual',2,25],['CNC Turning','automatic',6.5,75],['CNC Milling','automatic',8,85],['Move to Inspection','walk',.75,25],['First Off Inspection','inspection',5,30],['Deburr','automatic',3,60],['Move to Wash','walk',.75,25],['Wash','automatic',4,45],['Final Inspection','inspection',5,30],['Finished Goods','buffer',0,0]];state.nodes=seq.map((x,i)=>({id:'s'+i,name:x[0],type:x[1],cycle:x[2],cost:x[3],notes:'',x:i<5?60+i*245:60+(i-5)*245,y:i<5?100:390,colour:TYPES[x[1]].colour}));state.links=[];for(let i=0;i<9;i++)state.links.push({id:'sl'+i,from:'s'+i,to:'s'+(i+1)})}
function init(){Object.keys(TYPES).forEach(k=>{$('#taskType').insertAdjacentHTML('beforeend',`<option value="${k}">${TYPES[k].name}</option>`);$('#resourceType').insertAdjacentHTML('beforeend',`<option value="${k}">${TYPES[k].name}</option>`) });let saved;try{saved=JSON.parse(localStorage.getItem('mfd-stage1-autosave'))}catch{}if(saved?.nodes){state.nodes=saved.nodes;state.links=saved.links||[];state.customResources=saved.customResources||[];applyProject(saved.project||{})}else sample();renderAll();setTimeout(fitAll,50)}
$$('.toolbar [data-action]').forEach(b=>b.addEventListener('click',()=>{const a=b.dataset.action;({new:newProject,open:()=>$('#fileInput').click(),save:saveLocal,export:exportFile,print:()=>window.print(),undo,redo,fit:fitAll,zoomIn:()=>zoomAt(1.18),zoomOut:()=>zoomAt(.85),select:()=>setMode('select'),link:()=>setMode('link'),duplicate:duplicateSelected,delete:deleteSelected}[a]||(()=>{}))()}));
$('#fileInput').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{importData(JSON.parse(await f.text()))}catch(err){alert(err.message)}e.target.value=''});
['taskName','taskType','cycleTime','costPerHour','taskNotes'].forEach(id=>$('#'+id).addEventListener('change',updateSelectedFromForm));
$('#duplicateBtn').onclick=duplicateSelected;$('#deleteBtn').onclick=deleteSelected;
$('#addResourceBtn').onclick=()=>$('#resourceDialog').showModal();$('#resourceForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const type=$('#resourceType').value;snapshot();state.customResources.push({id:uid('r'),type,name:$('#resourceName').value.trim()||'Custom Resource',cycle:+$('#resourceCycle').value||0,cost:+$('#resourceCost').value||0,colour:$('#resourceColour').value});renderLibrary();$('#resourceDialog').close();toast('Resource added to library')});
$('#canvasViewport').addEventListener('pointerdown',canvasPointerDown);window.addEventListener('pointermove',pointerMove);window.addEventListener('pointerup',pointerUp);els.viewport.addEventListener('wheel',e=>{e.preventDefault();zoomAt(e.deltaY<0?1.1:.9,e.clientX,e.clientY)},{passive:false});
els.viewport.addEventListener('dragover',e=>e.preventDefault());els.viewport.addEventListener('drop',e=>{e.preventDefault();const raw=e.dataTransfer.getData('application/x-resource');if(!raw)return;const rect=els.viewport.getBoundingClientRect();addNodeFromResource(JSON.parse(raw),{x:(e.clientX-rect.left-state.panX)/state.zoom-105,y:(e.clientY-rect.top-state.panY)/state.zoom-66})});
$('#libraryToggle').onclick=()=>els.library.classList.toggle('open');$('#closeLibrary').onclick=()=>els.library.classList.remove('open');$('#closeInspector').onclick=()=>els.inspector.classList.remove('open');$('#menuBtn').onclick=()=>$('.toolbar').classList.toggle('open');
$$('.project-strip input,.project-strip select').forEach(el=>el.addEventListener('change',saveAutosave));window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();saveLocal()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo()}if(e.key==='Delete'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName))deleteSelected();if(e.key==='Escape'){linkStart=null;setMode('select')}});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));init();
