"use strict";const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const uid=(p='n')=>p+Date.now().toString(36)+Math.random().toString(36).slice(2,6);const clone=o=>JSON.parse(JSON.stringify(o));
const defaults={resources:[{id:'r1',name:'Load / Unload',type:'manual',manual:25,auto:0,walk:0,wait:0,cost:25,icon:'✋',colour:'#f3c400'},{id:'r2',name:'CNC Machining',type:'automatic',manual:0,auto:75,walk:0,wait:0,cost:75,icon:'⚙',colour:'#51aee0'},{id:'r3',name:'Walk / Transfer',type:'walk',manual:0,auto:0,walk:10,wait:0,cost:25,icon:'🚶',colour:'#78cf75'},{id:'r4',name:'Inspection',type:'inspection',manual:30,auto:0,walk:0,wait:0,cost:30,icon:'✓',colour:'#d49ae9'}]};
let S={version:4,project:{name:'Example Cell',customer:'Example Customer',component:'Gear Housing',volume:25000,shifts:2,hours:8,takt:60},lanes:[],resources:clone(defaults.resources),nodes:[],links:[],selected:null,selectedLink:null,mode:'select',zoom:1,panX:40,panY:40,layout:[],layoutSelected:null,layoutRoute:[],layoutZoom:1,layoutPanX:40,layoutPanY:40};let undo=[],redo=[],linkStart=null,drag=null,pan=null;const activePointers=new Map();let pinch=null;
function snap(){undo.push(clone({resources:S.resources,nodes:S.nodes,links:S.links}));if(undo.length>50)undo.shift();redo=[]}function toast(t){let x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1500)}
function inferType(n){if(n.type)return n.type;if((+n.auto||0)>0)return'automatic';if((+n.walk||0)>0)return'walk';if(/inspect/i.test(n.name||''))return'inspection';return'manual'}
function typeLabel(n){return({manual:'Manual',automatic:'Automatic',walk:'Walk / Transfer',inspection:'Inspection',buffer:'Buffer'})[inferType(n)]||'Manual'}
function duration(n){let t=inferType(n);return t==='automatic'?(+n.auto||0):t==='walk'?(+n.walk||0):(+n.manual||0)}
function setDuration(n,v){v=Math.max(0,+v||0);n.manual=n.auto=n.walk=n.wait=0;let t=inferType(n);if(t==='automatic')n.auto=v;else if(t==='walk')n.walk=v;else n.manual=v}
function total(n){return duration(n)}
function normaliseTypes(){S.resources=(S.resources||clone(defaults.resources)).map(r=>({...r,type:inferType(r)}));S.nodes=(S.nodes||[]).map(n=>({...n,type:inferType(n)}))}
function renderLibrary(){$('#library').innerHTML=S.resources.map(r=>`<div class="resourceCard" draggable="true" data-r="${r.id}"><div class="resourceIcon" style="background:${r.colour}">${r.icon}</div><div><b>${r.name}</b><small>${typeLabel(r)} · ${duration(r)} s</small></div></div>`).join('');$$('.resourceCard').forEach(c=>{c.ondragstart=e=>e.dataTransfer.setData('text/resource',c.dataset.r);c.onclick=()=>addNode(c.dataset.r,320+Math.random()*120,200+Math.random()*120)})}
function renderLanes(){}
function addNode(id,x,y){let r=S.resources.find(v=>v.id===id);if(!r)return;snap();S.nodes.push({id:uid(),name:r.name,type:inferType(r),manual:0,auto:0,walk:0,wait:0,cost:r.cost,notes:'',icon:r.icon,colour:r.colour,x,y,w:200,h:100});setDuration(S.nodes.at(-1),duration(r));S.selected=S.nodes.at(-1).id;renderAll()}
const PORTS={lt:[0,.25],lm:[0,.5],lb:[0,.75],rt:[1,.25],rm:[1,.5],rb:[1,.75],tc:[.5,0],bc:[.5,1]};
function portPoint(n,key){let p=PORTS[key]||PORTS.rm;return{x:n.x+n.w*p[0],y:n.y+n.h*p[1]}}
function renderNodes(){let box=$('#nodes');box.innerHTML='';S.nodes.forEach(n=>{let d=document.createElement('div');d.className='node'+(S.selected===n.id?' selected':'')+((S.mode==='link'||S.mode==='deleteLink')?' portsVisible':'');d.style.left=n.x+'px';d.style.top=n.y+'px';d.dataset.id=n.id;let ports=Object.keys(PORTS).map(k=>`<span class="port p-${k}" data-port="${k}" title="Connection point"></span>`).join('');d.innerHTML=`${ports}<div class="icon" style="background:${n.colour}">${n.icon}</div><div><h3>${n.name}</h3><div class="processType">${typeLabel(n)}</div><div class="time">${typeLabel(n)} time: <b>${duration(n)} s</b></div></div>`;d.onpointerdown=e=>nodeDown(e,n,d);d.querySelectorAll('.port').forEach(pt=>pt.onpointerdown=e=>portDown(e,n,pt.dataset.port));box.appendChild(d)})}
function portDown(e,n,port){e.stopPropagation();e.preventDefault();if(S.mode!=='link'){S.selected=n.id;S.selectedLink=null;renderAll();return}if(!linkStart){linkStart={nodeId:n.id,port};S.selected=n.id;toast('Select a destination connection point')}else if(linkStart.nodeId!==n.id){if(!S.links.some(l=>l.from===linkStart.nodeId&&l.to===n.id&&l.fromPort===linkStart.port&&l.toPort===port)){snap();S.links.push({id:uid('l'),from:linkStart.nodeId,to:n.id,fromPort:linkStart.port,toPort:port})}linkStart=null;renderAll()}}
function nodeDown(e,n,el){e.stopPropagation();if(e.target.classList.contains('port'))return;if(S.mode==='link'){let defaultPort=linkStart?'lm':'rm';portDown(e,n,defaultPort);return}if(S.mode==='deleteLink'){toast('Tap a highlighted link to delete it');return}S.selected=n.id;S.selectedLink=null;drag={id:n.id,dx:e.clientX-(n.x*S.zoom+S.panX),dy:e.clientY-(n.y*S.zoom+S.panY)};el.setPointerCapture?.(e.pointerId);renderAll()}
function distance(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
window.addEventListener('pointermove',e=>{if(activePointers.has(e.pointerId)){activePointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(activePointers.size===2){let pts=[...activePointers.values()],d=distance(pts[0],pts[1]),cx=(pts[0].x+pts[1].x)/2,cy=(pts[0].y+pts[1].y)/2;if(!pinch)pinch={d,zoom:S.zoom,worldX:(cx-S.panX)/S.zoom,worldY:(cy-S.panY)/S.zoom};let nz=Math.min(2.5,Math.max(.25,pinch.zoom*d/pinch.d));S.zoom=nz;S.panX=cx-pinch.worldX*nz;S.panY=cy-pinch.worldY*nz;transform();return}}if(drag){let n=S.nodes.find(x=>x.id===drag.id);n.x=(e.clientX-S.panX-drag.dx)/S.zoom;n.y=(e.clientY-S.panY-drag.dy)/S.zoom;renderNodes();renderLinks()}else if(pan){S.panX=e.clientX-pan.x;S.panY=e.clientY-pan.y;transform()}});
window.addEventListener('pointerup',e=>{activePointers.delete(e.pointerId);if(activePointers.size<2)pinch=null;drag=null;pan=null});window.addEventListener('pointercancel',e=>{activePointers.delete(e.pointerId);pinch=null;drag=null;pan=null});
function orthogonalPath(ap,bp){let sx=ap.x,sy=ap.y,tx=bp.x,ty=bp.y,midX=(sx+tx)/2,midY=(sy+ty)/2;if(Math.abs(tx-sx)>=Math.abs(ty-sy))return `M${sx},${sy} L${midX},${sy} L${midX},${ty} L${tx},${ty}`;return `M${sx},${sy} L${sx},${midY} L${tx},${midY} L${tx},${ty}`}
function removeLink(id){snap();S.links=S.links.filter(l=>l.id!==id);S.selectedLink=null;setMode('select');renderAll();toast('Link deleted')}
function renderLinks(){let svg=$('#links');svg.innerHTML='<defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="9" markerHeight="9" orient="auto" markerUnits="strokeWidth"><path d="M 0 0 L 10 5 L 0 10 z" fill="#f3c400"/></marker><marker id="arrowSelected" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="10" markerHeight="10" orient="auto" markerUnits="strokeWidth"><path d="M 0 0 L 10 5 L 0 10 z" fill="#ffffff"/></marker></defs>';S.links.forEach(l=>{let a=S.nodes.find(n=>n.id===l.from),b=S.nodes.find(n=>n.id===l.to);if(!a||!b)return;let ap=portPoint(a,l.fromPort||'rm'),bp=portPoint(b,l.toPort||'lm'),path=orthogonalPath(ap,bp);let hit=document.createElementNS('http://www.w3.org/2000/svg','path');hit.setAttribute('d',path);hit.setAttribute('class','linkHit'+(S.mode==='deleteLink'?' deleteReady':''));hit.onclick=e=>{e.stopPropagation();if(S.mode==='deleteLink'){removeLink(l.id);return}S.selected=null;S.selectedLink=l.id;renderAll()};hit.oncontextmenu=e=>{e.preventDefault();e.stopPropagation();if(confirm('Delete this link?'))removeLink(l.id)};let hold;hit.onpointerdown=e=>{if(e.pointerType==='touch')hold=setTimeout(()=>{if(confirm('Delete this link?'))removeLink(l.id)},650)};hit.onpointerup=hit.onpointercancel=()=>clearTimeout(hold);let line=document.createElementNS('http://www.w3.org/2000/svg','path');line.setAttribute('d',path);line.setAttribute('class','linkLine'+(S.selectedLink===l.id?' selected':'')+(S.mode==='deleteLink'?' deleteReady':''));line.setAttribute('marker-end',S.selectedLink===l.id?'url(#arrowSelected)':'url(#arrow)');svg.append(hit,line)})}
function transform(){$('#world').style.transform=`translate(${S.panX}px,${S.panY}px) scale(${S.zoom})`;$('#zoom').textContent=Math.round(S.zoom*100)+'%'}
function editor(){let n=S.nodes.find(x=>x.id===S.selected);$('#taskForm').classList.toggle('hidden',!n);$('#empty').classList.toggle('hidden',!!n);if(!n)return;$('#taskName').value=n.name;$('#processType').value=typeLabel(n);$('#timeLabel').textContent=typeLabel(n)+' time (s)';$('#taskTime').value=duration(n);$('#cost').value=n.cost;$('#notes').value=n.notes}
function summary(){let cyc=S.nodes.reduce((a,n)=>a+total(n),0),manual=S.nodes.reduce((a,n)=>a+(+n.manual||0)+(+n.walk||0),0);$('#taskCount').textContent=S.nodes.length+' tasks';$('#cycleTotal').textContent=cyc.toFixed(1)+' s cycle';$('#utilTotal').textContent=(cyc?manual/cyc*100:0).toFixed(0)+'% operator';$('#selection').textContent=S.selected?'Task selected':S.selectedLink?'Link selected':'No selection'}
function renderAll(){renderLibrary();renderLanes();renderNodes();renderLinks();transform();editor();summary();drawChart()}
['taskName','taskTime','cost','notes'].forEach(id=>$('#'+id).oninput=()=>{let n=S.nodes.find(x=>x.id===S.selected);if(!n)return;if(id==='taskName')n.name=$('#taskName').value;else if(id==='taskTime')setDuration(n,$('#taskTime').value);else if(id==='cost')n.cost=Math.max(0,+$('#cost').value||0);else n.notes=$('#notes').value;renderNodes();renderLinks();summary();drawChart()});
function deleteSel(){if(S.selected){snap();S.nodes=S.nodes.filter(n=>n.id!==S.selected);S.links=S.links.filter(l=>l.from!==S.selected&&l.to!==S.selected);S.selected=null}else if(S.selectedLink){snap();S.links=S.links.filter(l=>l.id!==S.selectedLink);S.selectedLink=null}renderAll()}$('#delete').onclick=deleteSel;$('#duplicate').onclick=()=>{let n=S.nodes.find(x=>x.id===S.selected);if(!n)return;snap();let c={...clone(n),id:uid(),name:n.name+' Copy',x:n.x+35,y:n.y+35};S.nodes.push(c);S.selected=c.id;renderAll()};
$('#viewport').ondragover=e=>e.preventDefault();$('#viewport').ondrop=e=>{e.preventDefault();let r=e.dataTransfer.getData('text/resource'),b=$('#viewport').getBoundingClientRect();addNode(r,(e.clientX-b.left-S.panX)/S.zoom,(e.clientY-b.top-S.panY)/S.zoom)};$('#viewport').onpointerdown=e=>{activePointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(e.target===$('#viewport')||e.target===$('#world')||e.target===$('#nodes')||e.target===$('#links')){S.selected=null;S.selectedLink=null;if(activePointers.size===1)pan={x:e.clientX-S.panX,y:e.clientY-S.panY};renderAll()}};$('#viewport').onwheel=e=>{e.preventDefault();let b=$('#viewport').getBoundingClientRect(),mx=e.clientX-b.left,my=e.clientY-b.top,wx=(mx-S.panX)/S.zoom,wy=(my-S.panY)/S.zoom,nz=Math.min(2.5,Math.max(.25,S.zoom*(e.deltaY<0?1.12:.89)));S.zoom=nz;S.panX=mx-wx*nz;S.panY=my-wy*nz;transform()};document.addEventListener('gesturestart',e=>e.preventDefault(),{passive:false});document.addEventListener('gesturechange',e=>e.preventDefault(),{passive:false});document.addEventListener('touchmove',e=>{if(e.target.closest('#viewport'))e.preventDefault()},{passive:false});
function projectFromUi(){S.project={name:$('#projectName').value,customer:$('#customer').value,component:$('#component').value,volume:+$('#volume').value||0,shifts:+$('#shifts').value||1,hours:+$('#hours').value||8,takt:+$('#takt').value||60}}function uiFromProject(){let p=S.project;$('#projectName').value=p.name||'';$('#customer').value=p.customer||'';$('#component').value=p.component||'';$('#volume').value=p.volume||0;$('#shifts').value=p.shifts||1;$('#hours').value=p.hours||8;$('#takt').value=p.takt||60}
function download(){projectFromUi();let blob=new Blob([JSON.stringify(S,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(S.project.name||'ManufacturingFlow')+'_V3.mflow';a.click();URL.revokeObjectURL(a.href)}function saveLocal(){projectFromUi();localStorage.setItem('mfd-v3',JSON.stringify(S));toast('Saved locally')}function newProject(){if(!confirm('Start a new project?'))return;S={...S,project:{name:'Untitled Cell',customer:'',component:'',volume:0,shifts:1,hours:8,takt:60},lanes:[],resources:clone(defaults.resources),nodes:[],links:[],selected:null,selectedLink:null};uiFromProject();renderAll()}
function setMode(a){S.mode=a;linkStart=null;$$('[data-a=select],[data-a=link],[data-a=deleteLink]').forEach(x=>x.classList.toggle('active',x.dataset.a===a));$('#modeHint').textContent=a==='link'?'Link mode: choose source and destination ports':a==='deleteLink'?'Delete link mode: tap a highlighted route':'Select mode';renderNodes();renderLinks()}
$$('[data-a]').forEach(b=>b.onclick=()=>{let a=b.dataset.a;if(a==='new')newProject();if(a==='save')saveLocal();if(a==='export')download();if(a==='open')$('#fileInput').click();if(a==='print')window.print();if(a==='delete')deleteSel();if(a==='deleteLink')setMode('deleteLink');if(a==='select'||a==='link')setMode(a);if(a==='fit'){S.zoom=.65;S.panX=30;S.panY=30;transform()}if(a==='undo'&&undo.length){redo.push(clone({lanes:S.lanes,resources:S.resources,nodes:S.nodes,links:S.links}));Object.assign(S,undo.pop());renderAll()}if(a==='redo'&&redo.length){undo.push(clone({lanes:S.lanes,resources:S.resources,nodes:S.nodes,links:S.links}));Object.assign(S,redo.pop());renderAll()}});$('#fileInput').onchange=async e=>{try{let x=JSON.parse(await e.target.files[0].text());S={...S,...x,selected:null,selectedLink:null};normaliseTypes();uiFromProject();renderAll();toast('Project opened')}catch{alert('Unable to open file')}};
$$('[data-tab]').forEach(b=>b.onclick=()=>{$$('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));$('#mapView').classList.toggle('hidden',b.dataset.tab!=='map');$('#standardView').classList.toggle('hidden',b.dataset.tab!=='standard');$('#layoutView').classList.toggle('hidden',b.dataset.tab!=='layout');drawChart();if(b.dataset.tab==='layout')renderLayout()});
$('#customBtn').onclick=()=>$('#resourceDialog').showModal();$('#saveResource').onclick=e=>{e.preventDefault();let type=$('#resType').value,time=Math.max(0,+$('#resTime').value||0),icons={manual:'✋',automatic:'⚙',walk:'🚶',inspection:'✓'},colours={manual:'#f3c400',automatic:'#51aee0',walk:'#78cf75',inspection:'#d49ae9'};let r={id:uid('r'),name:$('#resName').value||'New Operation',type,manual:0,auto:0,walk:0,wait:0,cost:25,icon:icons[type],colour:colours[type]};setDuration(r,time);S.resources.push(r);$('#resourceDialog').close();normaliseTypes();renderAll()};
function sequence(){if(!S.nodes.length)return[];let incoming=new Map(S.nodes.map(n=>[n.id,0]));S.links.forEach(l=>incoming.set(l.to,(incoming.get(l.to)||0)+1));let q=S.nodes.filter(n=>!incoming.get(n.id)).sort((a,b)=>a.x-b.x),out=[],seen=new Set;while(q.length){let n=q.shift();if(seen.has(n.id))continue;seen.add(n.id);out.push(n);S.links.filter(l=>l.from===n.id).forEach(l=>{let b=S.nodes.find(n=>n.id===l.to);if(b)q.push(b)})}S.nodes.filter(n=>!seen.has(n.id)).sort((a,b)=>a.x-b.x).forEach(n=>out.push(n));return out}
function drawChart(){if(!$('#chart'))return;projectFromUi();let px=+$('#scale').value||2,takt=+$('#takt').value||60,seq=sequence(),max=Math.max(takt,...seq.map(duration),60),width=Math.max(900,max*px+80),html=`<div class="axis" style="width:${width}px">`;for(let t=0;t<=max;t+=10)html+=`<span class="tick" style="left:${t*px}px">${t}s</span>`;html+='</div>';seq.forEach(n=>{let k=inferType(n)==='automatic'?'automatic':inferType(n)==='walk'?'walking':'manual',v=duration(n);html+=`<div class="chartRow" style="width:${width}px"><div class="rowLabel">${n.name}<small>${typeLabel(n)}</small></div><div class="bar ${k}" style="left:0;width:${Math.max(3,v*px)}px">${v}s</div></div>`});if($('#showTakt').checked)html+=`<div class="taktLine" style="left:${180+takt*px}px" title="Takt ${takt}s"></div>`;$('#chart').style.width=(width+180)+'px';$('#chart').innerHTML=html;$('#chartTitle').textContent=`${S.project.name||''} · Takt ${takt}s`;let longest=[...seq].sort((a,b)=>duration(b)-duration(a))[0],manual=seq.filter(n=>['manual','inspection'].includes(inferType(n))).reduce((a,n)=>a+duration(n),0),cycle=seq.reduce((a,n)=>a+duration(n),0);$('#stdSummary').innerHTML=`<div class="summaryCard">Longest task <b>${longest?longest.name:'-'}</b></div><div class="summaryCard">Longest time <b>${longest?duration(longest).toFixed(1):0}s</b></div><div class="summaryCard">Manual share <b>${cycle?(manual/cycle*100).toFixed(1):0}%</b></div><div class="summaryCard">Takt status <b>${longest&&duration(longest)>takt?'OVER TAKT':'WITHIN TAKT'}</b></div>`}
function layoutPx(){return +$('#layoutScale').value||30}function layoutGridPx(){return Math.max(.25,+$('#layoutGrid').value||1)*layoutPx()}
function layoutDimensions(it){let w=it.width*layoutPx(),h=it.depth*layoutPx();if(+it.rotation%180===90)[w,h]=[h,w];return{w,h}}
function layoutCentre(it){let d=layoutDimensions(it);return{x:it.x+d.w/2,y:it.y+d.h/2}}
function renderLayout(){ensureLayoutState();let px=layoutPx(),grid=layoutGridPx();$('#layoutWorld').style.backgroundSize=`${grid}px ${grid}px`;let box=$('#layoutItems');box.innerHTML='';S.layout.forEach(it=>{let d=layoutDimensions(it),clear=it.clearance*px;let wrap=document.createElement('div');wrap.className='clearanceBox';wrap.style.left=(it.x-clear)+'px';wrap.style.top=(it.y-clear)+'px';wrap.style.width=(d.w+clear*2)+'px';wrap.style.height=(d.h+clear*2)+'px';box.appendChild(wrap);let e=document.createElement('div');e.className=`layoutItem ${String(it.kind).toLowerCase()}${S.layoutSelected===it.id?' selected':''}${S.layoutRoute.includes(it.id)?' routePick':''}`;e.dataset.id=it.id;e.style.left=it.x+'px';e.style.top=it.y+'px';e.style.width=Math.max(35,d.w)+'px';e.style.height=Math.max(35,d.h)+'px';e.innerHTML=`<div><b>${it.name}</b><small>${it.width.toFixed(1)} × ${it.depth.toFixed(1)} m · ${it.rotation}°</small></div>`;e.onpointerdown=ev=>layoutItemDown(ev,it,e);box.appendChild(e)});drawLayoutRoute();layoutTransform();layoutEditor();layoutSummary()}
function layoutItemDown(e,it,el){e.stopPropagation();e.preventDefault();if(layoutRouteMode){if(!S.layoutRoute.includes(it.id))S.layoutRoute.push(it.id);else if(S.layoutRoute.at(-1)===it.id)S.layoutRoute.pop();renderLayout();return}S.layoutSelected=it.id;let b=$('#layoutViewport').getBoundingClientRect(),p={x:(e.clientX-b.left-S.layoutPanX)/S.layoutZoom,y:(e.clientY-b.top-S.layoutPanY)/S.layoutZoom};layoutDrag={it,dx:p.x-it.x,dy:p.y-it.y,pid:e.pointerId};el.setPointerCapture(e.pointerId);renderLayout()}
function drawLayoutRoute(){let svg=$('#layoutRoutes');svg.innerHTML=`<defs><marker id="routeArrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="#78cf75"/></marker></defs>`;let total=0;for(let i=1;i<S.layoutRoute.length;i++){let a=S.layout.find(x=>x.id===S.layoutRoute[i-1]),b=S.layout.find(x=>x.id===S.layoutRoute[i]);if(!a||!b)continue;let p=layoutCentre(a),q=layoutCentre(b),midx=(p.x+q.x)/2,dist=Math.hypot(q.x-p.x,q.y-p.y)/layoutPx();total+=dist;let path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',`M${p.x},${p.y} L${q.x},${q.y}`);path.setAttribute('class','routeLine');svg.appendChild(path);let tx=document.createElementNS('http://www.w3.org/2000/svg','text');tx.setAttribute('x',midx);tx.setAttribute('y',(p.y+q.y)/2-8);tx.setAttribute('class','routeLabel');tx.textContent=dist.toFixed(1)+' m';svg.appendChild(tx)}return total}
function layoutTransform(){$('#layoutWorld').style.transform=`translate(${S.layoutPanX}px,${S.layoutPanY}px) scale(${S.layoutZoom})`}
function layoutEditor(){let it=S.layout.find(x=>x.id===S.layoutSelected);$('#layoutForm').classList.toggle('hidden',!it);$('#layoutEmpty').classList.toggle('hidden',!!it);$('#layoutSelection').textContent=it?it.name:'No resource selected';if(!it)return;$('#layoutName').value=it.name;$('#layoutWidth').value=it.width;$('#layoutDepth').value=it.depth;$('#layoutClearance').value=it.clearance;$('#layoutRotation').value=it.rotation;$('#layoutKind').value=it.kind;$('#layoutNotes').value=it.notes||''}
function layoutSummary(){let px=layoutPx(),route=drawLayoutRoute(),minX=Infinity,minY=Infinity,maxX=0,maxY=0,area=0;S.layout.forEach(it=>{let d=layoutDimensions(it),c=it.clearance*px;minX=Math.min(minX,it.x-c);minY=Math.min(minY,it.y-c);maxX=Math.max(maxX,it.x+d.w+c);maxY=Math.max(maxY,it.y+d.h+c);area+=it.width*it.depth});let cw=S.layout.length?(maxX-minX)/px:0,ch=S.layout.length?(maxY-minY)/px:0,walkSec=route/1.2;$('#layoutSummary').innerHTML=`<div class="layoutSummaryCard">Resources <b>${S.layout.length}</b></div><div class="layoutSummaryCard">Cell envelope <b>${cw.toFixed(1)} × ${ch.toFixed(1)} m</b></div><div class="layoutSummaryCard">Footprint area <b>${area.toFixed(1)} m²</b></div><div class="layoutSummaryCard">Walking route <b>${route.toFixed(1)} m</b></div><div class="layoutSummaryCard">Walking time <b>${walkSec.toFixed(1)} s</b></div>`}
['layoutName','layoutWidth','layoutDepth','layoutClearance','layoutRotation','layoutKind','layoutNotes'].forEach(id=>$('#'+id).oninput=()=>{let it=S.layout.find(x=>x.id===S.layoutSelected);if(!it)return;let map={layoutName:'name',layoutWidth:'width',layoutDepth:'depth',layoutClearance:'clearance',layoutRotation:'rotation',layoutKind:'kind',layoutNotes:'notes'},v=$('#'+id).value;if(['layoutWidth','layoutDepth','layoutClearance','layoutRotation'].includes(id))v=+v||0;it[map[id]]=v;renderLayout()});
$('#layoutScale').oninput=renderLayout;$('#layoutGrid').oninput=renderLayout;$('#syncLayout').onclick=syncLayout;$('#addLayoutItem').onclick=addLayoutResource;$('#deleteLayout').onclick=()=>{if(!S.layoutSelected)return;S.layout=S.layout.filter(x=>x.id!==S.layoutSelected);S.layoutRoute=S.layoutRoute.filter(id=>id!==S.layoutSelected);S.layoutSelected=null;renderLayout()};$('#clearRoute').onclick=()=>{S.layoutRoute=[];renderLayout()};$('#routeMode').onclick=()=>{layoutRouteMode=!layoutRouteMode;$('#routeMode').textContent=layoutRouteMode?'Finish route':'Start route';$('#routeMode').classList.toggle('primary',layoutRouteMode);$('#layoutHint').textContent=layoutRouteMode?'Tap resources in walking order':'Drag resources to position them'};$('#fitLayout').onclick=()=>{S.layoutZoom=.8;S.layoutPanX=30;S.layoutPanY=30;layoutTransform()};
$('#layoutViewport').onpointerdown=e=>{layoutPointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(e.target===$('#layoutViewport')||e.target===$('#layoutWorld')||e.target===$('#layoutItems')||e.target===$('#layoutRoutes')){S.layoutSelected=null;layoutPan={x:e.clientX-S.layoutPanX,y:e.clientY-S.layoutPanY,pid:e.pointerId};renderLayout()}};
window.addEventListener('pointermove',e=>{if(layoutDrag&&e.pointerId===layoutDrag.pid){let b=$('#layoutViewport').getBoundingClientRect(),x=(e.clientX-b.left-S.layoutPanX)/S.layoutZoom-layoutDrag.dx,y=(e.clientY-b.top-S.layoutPanY)/S.layoutZoom-layoutDrag.dy;if($('#snapGrid').checked){let g=layoutGridPx();x=Math.round(x/g)*g;y=Math.round(y/g)*g}layoutDrag.it.x=Math.max(0,x);layoutDrag.it.y=Math.max(0,y);renderLayout()}else if(layoutPan&&e.pointerId===layoutPan.pid){S.layoutPanX=e.clientX-layoutPan.x;S.layoutPanY=e.clientY-layoutPan.y;layoutTransform()}});
window.addEventListener('pointerup',e=>{if(layoutDrag&&e.pointerId===layoutDrag.pid)layoutDrag=null;if(layoutPan&&e.pointerId===layoutPan.pid)layoutPan=null;layoutPointers.delete(e.pointerId)});
$('#layoutViewport').onwheel=e=>{e.preventDefault();let b=$('#layoutViewport').getBoundingClientRect(),mx=e.clientX-b.left,my=e.clientY-b.top,wx=(mx-S.layoutPanX)/S.layoutZoom,wy=(my-S.layoutPanY)/S.layoutZoom,nz=Math.min(2.5,Math.max(.25,S.layoutZoom*(e.deltaY<0?1.12:.89)));S.layoutZoom=nz;S.layoutPanX=mx-wx*nz;S.layoutPanY=my-wy*nz;layoutTransform()};
ensureLayoutState();


// ---- V4 DIGITAL TWIN SIMULATION ----
let SIM={running:false,time:0,last:0,nextRelease:0,produced:0,parts:[],busy:{},busyTime:{},waitingTime:0,manualTime:0,autoTime:0,walkTime:0,raf:0};
const simIcon=n=>{let x=(n.name||'').toLowerCase();if(x.includes('load')||x.includes('unload'))return '✋';if(x.includes('walk')||x.includes('transfer'))return '🚶';if(x.includes('inspect'))return '✓';if(x.includes('buffer'))return '▤';return '⚙'};
function orderedNodes(){let out=[],seen=new Set(),incoming=new Map(S.nodes.map(n=>[n.id,0]));S.links.forEach(l=>incoming.set(l.to,(incoming.get(l.to)||0)+1));let q=S.nodes.filter(n=>(incoming.get(n.id)||0)===0);while(q.length){let n=q.shift();if(seen.has(n.id))continue;seen.add(n.id);out.push(n);S.links.filter(l=>l.from===n.id).forEach(l=>{let t=S.nodes.find(x=>x.id===l.to);if(t)q.push(t)})}S.nodes.forEach(n=>{if(!seen.has(n.id))out.push(n)});return out}
function initSimulationView(){renderSimulation();updateSimStats()}
function renderSimulation(){let box=$('#simNodes'),svg=$('#simLinks');if(!box||!svg)return;box.innerHTML='';svg.innerHTML='<defs><marker id="simArrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="#f3c400"/></marker></defs>';S.nodes.forEach(n=>{let e=document.createElement('div');let state=SIM.busy[n.id]>SIM.time?'running':'waiting';e.className='simNode '+state;e.id='sim-'+n.id;e.style.left=n.x+'px';e.style.top=n.y+'px';let total=(+n.manual||0)+(+n.auto||0)+(+n.walk||0)+(+n.wait||0);e.innerHTML=`<div class="simIcon">${simIcon(n)}</div><b>${n.name}</b><small>${typeLabel(n)} · ${duration(n).toFixed(1)} s</small><small class="nodeState">${state==='running'?'RUNNING':'READY'}</small>`;box.appendChild(e)});S.links.forEach(l=>{let a=S.nodes.find(n=>n.id===l.from),b=S.nodes.find(n=>n.id===l.to);if(!a||!b)return;let p={x:a.x+190,y:a.y+47},q={x:b.x,y:b.y+47},m=(p.x+q.x)/2;let path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',`M${p.x},${p.y} H${m} V${q.y} H${q.x}`);path.setAttribute('stroke','#f3c400');path.setAttribute('stroke-width','3');path.setAttribute('fill','none');path.setAttribute('marker-end','url(#simArrow)');svg.appendChild(path)});updatePartsVisual()}
function nodeDuration(n){return Math.max(.2,(+n.manual||0)+(+n.auto||0)+(+n.walk||0)+(+n.wait||0))}
function spawnPart(){let order=orderedNodes();if(!order.length)return;SIM.parts.push({id:uid('part'),index:0,progress:0,wait:0});}
function simTick(ts){if(!SIM.running)return;if(!SIM.last)SIM.last=ts;let dt=Math.min(.1,(ts-SIM.last)/1000)*(+$('#simSpeed').value||1);SIM.last=ts;advanceSimulation(dt);SIM.raf=requestAnimationFrame(simTick)}
function advanceSimulation(dt){SIM.time+=dt;let interval=Math.max(1,+$('#releaseInterval').value||45);while(SIM.time>=SIM.nextRelease){spawnPart();SIM.nextRelease+=interval}let order=orderedNodes();for(let p of SIM.parts){let n=order[p.index];if(!n)continue;let dur=nodeDuration(n);let laneBusy=SIM.busy[n.id]||0;if(p.progress===0&&laneBusy>SIM.time){p.wait+=dt;SIM.waitingTime+=dt;continue}if(p.progress===0)SIM.busy[n.id]=SIM.time+dur;p.progress+=dt/dur;SIM.busyTime[n.id]=(SIM.busyTime[n.id]||0)+dt;let sum=(+n.manual||0)+(+n.auto||0)+(+n.walk||0)+(+n.wait||0)||1;SIM.manualTime+=dt*(+n.manual||0)/sum;SIM.autoTime+=dt*(+n.auto||0)/sum;SIM.walkTime+=dt*(+n.walk||0)/sum;if(p.progress>=1){p.index++;p.progress=0;if(p.index>=order.length){p.done=true;SIM.produced++}}}SIM.parts=SIM.parts.filter(p=>!p.done);$('#simScrub').value=Math.min(3600,SIM.time);renderSimulation();updateSimStats();}
function updatePartsVisual(){let layer=$('#simParts');if(!layer)return;layer.innerHTML='';if(!$('#showParts').checked)return;let order=orderedNodes();SIM.parts.forEach(p=>{let a=order[p.index],b=order[Math.min(p.index+1,order.length-1)];if(!a)return;let x=a.x+95,y=a.y+47;if(b&&p.progress>.78){let t=(p.progress-.78)/.22;x+=(b.x-a.x)*t;y+=(b.y-a.y)*t}let e=document.createElement('div');e.className='simPart';e.style.left=x+'px';e.style.top=y+'px';layer.appendChild(e)})}
function fmtTime(s){s=Math.floor(s);return [Math.floor(s/3600),Math.floor(s/60)%60,s%60].map(x=>String(x).padStart(2,'0')).join(':')}
function updateSimStats(){if(!$('#liveStats'))return;$('#simClock').textContent=fmtTime(SIM.time);$('#simProduced').textContent=SIM.produced+' finished';let th=SIM.time?SIM.produced/SIM.time*3600:0,wip=SIM.parts.length;let util=Object.values(SIM.busyTime).reduce((a,b)=>a+b,0)/(Math.max(1,SIM.time)*Math.max(1,S.lanes.length))*100;$('#liveStats').innerHTML=`<div class="statCard">Parts produced<b>${SIM.produced}</b></div><div class="statCard">Throughput<b>${th.toFixed(1)} / hr</b></div><div class="statCard">Current WIP<b>${wip}</b></div><div class="statCard">Resource utilisation<b>${util.toFixed(1)}%</b></div><div class="statCard">Waiting time<b>${SIM.waitingTime.toFixed(1)} s</b></div>`;$('#resourceStats').innerHTML=S.lanes.map(l=>{let u=SIM.time?(SIM.busyTime[l.id]||0)/SIM.time*100:0;return `<div class="statCard"><span class="statusDot" style="background:${(SIM.busy[l.id]||0)>SIM.time?'#55d47a':'#f3c400'}"></span>${l.name}<b>${Math.min(100,u).toFixed(0)}%</b></div>`}).join('');$('#simWarnings').innerHTML=SIM.parts.length>Math.max(1,+$('#bufferCapacity').value||5)?'<div class="statCard"><b>BUFFER LIMIT</b>WIP exceeds configured capacity.</div>':'';renderAnalytics()}
function resetSimulation(){cancelAnimationFrame(SIM.raf);SIM={running:false,time:0,last:0,nextRelease:0,produced:0,parts:[],busy:{},busyTime:{},waitingTime:0,manualTime:0,autoTime:0,walkTime:0,raf:0};$('#simState').textContent='Stopped';renderSimulation();updateSimStats()}
$('#simPlay').onclick=()=>{if(SIM.running)return;SIM.running=true;SIM.last=0;$('#simState').textContent='Running';SIM.raf=requestAnimationFrame(simTick)};$('#simPause').onclick=()=>{SIM.running=false;cancelAnimationFrame(SIM.raf);$('#simState').textContent='Paused'};$('#simStep').onclick=()=>{SIM.running=false;advanceSimulation(1)};$('#simReset').onclick=resetSimulation;$('#showParts').oninput=renderSimulation;$('#showStates').oninput=renderSimulation;$('#printAnalytics').onclick=()=>window.print();
function renderAnalytics(){if(!$('#analyticsKpis'))return;let th=SIM.time?SIM.produced/SIM.time*3600:0,util=Object.values(SIM.busyTime).reduce((a,b)=>a+b,0)/(Math.max(1,SIM.time)*Math.max(1,S.lanes.length))*100;$('#analyticsKpis').innerHTML=`<div class="kpi">Completed<b>${SIM.produced}</b></div><div class="kpi">Throughput<b>${th.toFixed(1)}/h</b></div><div class="kpi">Average WIP<b>${SIM.parts.length}</b></div><div class="kpi">Utilisation<b>${util.toFixed(1)}%</b></div><div class="kpi">Waiting<b>${SIM.waitingTime.toFixed(0)}s</b></div>`;let rows=S.lanes.map(l=>{let u=SIM.time?(SIM.busyTime[l.id]||0)/SIM.time*100:0;return `<div class="barRow"><span>${l.name}</span><div class="barTrack"><div class="barFill" style="width:${Math.min(100,u)}%"></div></div><b>${Math.min(100,u).toFixed(0)}%</b></div>`}).join('');$('#utilChart').innerHTML=rows||'<p>Run the simulation to populate analytics.</p>';let total=SIM.manualTime+SIM.autoTime+SIM.walkTime+SIM.waitingTime||1;$('#timeBreakdown').innerHTML=[['Manual',SIM.manualTime],['Automatic',SIM.autoTime],['Walking',SIM.walkTime],['Waiting',SIM.waitingTime]].map(([n,v])=>`<div class="barRow"><span>${n}</span><div class="barTrack"><div class="barFill" style="width:${v/total*100}%"></div></div><b>${(v/total*100).toFixed(0)}%</b></div>`).join('');let bott=S.lanes.map(l=>({l,u:SIM.time?(SIM.busyTime[l.id]||0)/SIM.time:0})).sort((a,b)=>b.u-a.u)[0];$('#recommendations').innerHTML=bott?`<div class="statCard"><b>${bott.l.name}</b>Highest utilisation at ${(bott.u*100).toFixed(1)}%. Review cycle time, parallel capacity or operator allocation.</div><div class="statCard"><b>${SIM.parts.length>5?'Queue build-up detected':'Flow stable'}</b>${SIM.parts.length>5?'Increase downstream capacity or release parts less frequently.':'No sustained excessive WIP is currently visible.'}</div>`:'<p>Run the simulation to generate recommendations.</p>'}
